name: Deploy CNN-AI Backend

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'CNN-AI/**'
      - '.github/workflows/deploy-backend.yml'

jobs:
  build:
    runs-on: hostinger
    steps:
      - name: Git Checkout Repository
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Docker Build And Push Backend
        uses: docker/build-push-action@v6
        with:
          context: ./CNN-AI
          file: ./CNN-AI/Dockerfile
          push: true
          tags: |
            ${{ secrets.REGISTRY_URL }}/stevenlie14/skin-lesion-backend:latest

  deploy:
    runs-on: hostinger
    needs: build
    steps:
      - name: Git Checkout Repository
        uses: actions/checkout@v4

      - name: Import Deploy Secrets from Hashicorp
        uses: hashicorp/vault-action@v2
        with:
          method: 'userpass'
          url: ${{ secrets.VAULT_URL }}
          username: ${{ secrets.VAULT_USERNAME }}
          password: ${{ secrets.VAULT_PASSWORD}}
          tlsSkipVerify: true
          secrets: |
            ${{ secrets.VAULT_PATH }} *

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Deploy Backend Service
        env:
          REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
        run: |
          docker pull ${{ secrets.REGISTRY_URL }}/stevenlie14/skin-lesion-backend:latest
          docker compose -f docker-compose.yml stop backend
          docker compose -f docker-compose.yml rm -f backend
          docker compose -f docker-compose.yml up -d backend
          docker image prune -f
